# Generated by Django 5.0 on 2024-01-16 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='unlikes',
            new_name='dislikes',
        ),
    ]
